version: 2
jobs:
  build:
    docker:
      - image: silex/emacs:24
    steps:
      - checkout
      - run:
          name: Install Cask
          command: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - run:
          name: Run Tests
          command: PATH="$HOME/.cask/bin:$PATH" make
